version: "3"

tasks:
  build:
    cmds:
      - go build -v -o kjfttlib-service ./cmd/service

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  container:
    cmds:
      - docker build -t kjfttlib:local .
